baseURL = "https://willing123-png.github.io/willing123-png/"
languageCode = "zh-cn"
title = "Willing's Blog"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true